name: proyecto_protectora
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
     sdk: flutter
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.0.0
  go_router: ^16.2.4
  equatable: ^2.0.7
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  uuid: ^4.5.2
  google_fonts: ^6.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: NunitoSans
      fonts:
        - asset: assets/fonts/NunitoSans/NunitoSans-Italic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/NunitoSans/NunitoSans-VariableFont.ttf
          weight: 600

    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/Nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/Nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/Nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic

    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/Inter-Regular.otf
        - asset: assets/fonts/Inter/Inter-Italic.otf
          style: italic
        - asset: assets/fonts/Inter/Inter-Light-BETA.otf
          weight: 300
        - asset: assets/fonts/Inter/Inter-LightItalic-BETA.otf
          weight: 300
          style: italic
        - asset: assets/fonts/Inter/Inter-Medium.otf
          weight: 500
        - asset: assets/fonts/Inter/Inter-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/Inter/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter/Inter-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/Inter/Inter-Bold.otf
          weight: 700
        - asset: assets/fonts/Inter/Inter-BoldItalic.otf
          weight: 700
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Inter/Inter-ExtraBoldItalic.otf
          weight: 800
          style: italic
        - asset: assets/fonts/Inter/Inter-Black.otf
          weight: 900
        - asset: assets/fonts/Inter/Inter-BlackItalic.otf
          weight: 900
          style: italic
        - asset: assets/fonts/Inter/Inter-ExtraLight-BETA.otf
          weight: 200
        - asset: assets/fonts/Inter/Inter-ExtraLightItalic-BETA.otf
          weight: 200
          style: italic
        - asset: assets/fonts/Inter/Inter-Thin-BETA.otf
          weight: 100
        - asset: assets/fonts/Inter/Inter-ThinItalic-BETA.otf
          weight: 100
          style: italic

  
